version: '2.1'

services:
  eureka-server:
    build: eureka-server/
    mem_limit: 512m
    ports:
    - 8761:8761
  config-server:
    build: config-server/
    mem_limit: 512m
    ports:
    - 8888:8888
  gateway:
    build: gateway/
    mem_limit: 512m
    ports:
    - 8086:8086
  checkout-service:
    build: checkout-service/
    mem_limit: 512m
    ports:
      - 8081:8080
  products: 
    build: products-services/
    mem_limit: 512m
    ports:
    - 8084:8080
  payments-service:
    build: payments/
    mem_limit: 512m
    ports:
    - 8082:8080
  notifications:
    build: notification/
    mem_limit: 512m
    ports:
    - 8083:8080
  rabbit-mq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      start-dev
