server.port=8888
spring.application.name=config-service
eureka.instance.hostname=localhost
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.hostKeyAlgorithm=ssh-rsa
spring.cloud.config.server.git.uri= git@github.com:MauroTapia/config-server.git
spring.cloud.config.server.git.privateKey=
